version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=dev
      - DATABASE_PASSWORD=dev
      - DATABASE_NAME=docker_dev
      - DATABASE_PORT=3306
      - DATABASE_URL="mysql://root:rootpassword@db:3306/docker_dev"
      - DATABASE_ROOT_PASSWORD=rootpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: docker_dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: